name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      # Guardrails & posture (no secrets, all safe defaults)
      STRICT_JSON: "1"
      ABSTAIN_ON_NO_EVIDENCE: "1"
      MIN_SCORE: "0.40"
      # Ensure no accidental live Google calls in CI (wrappers are mocked in tests)
      GOOGLE_SA_JSON_PATH: ""
      GSHEET_ID: ""
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PYTHONUNBUFFERED: "1"
      PYTHONHASHSEED: "0"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install system deps (if any)
        run: |
          python -V

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          # fallback for editable project
          if [ -f pyproject.toml ] || [ -f setup.cfg ] || [ -f setup.py ]; then pip install -e .; fi
          # pytest always installed for CI
          pip install pytest

      - name: Run unit & smoke tests (quiet)
        run: |
          pytest -q

      - name: Show failing logs (only on failure)
        if: failure()
        run: |
          echo "==== Pytest cache/artifacts (if any) ===="
          ls -la .pytest_cache || true
