name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f pyproject.toml ]; then pip install -e ".[dev]" || pip install -e .; fi
          pip install pytest pytest-cov
      - name: Run pytest (offline)
        env:
          NO_NETWORK: "1"
          OPENAI_API_MOCK: "1"
          OPENAI_API_KEY: "dummy"   # satisfy OpenAI SDK import
          MIN_SCORE: "0.0"          # lenient for offline CI
          PYTHONPATH: ${{ github.workspace }}
        run: |
          mkdir -p artifacts/test-results
          pytest -q --junitxml=artifacts/test-results/junit.xml 2>&1 | tee artifacts/test-results/pytest-stdout.txt
      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: legacy-test-results
          path: artifacts/test-results/*
          if-no-files-found: warn
