name: Week-6 Phase-4 — Offline CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "app/**"
      - "tests/**"
      - "docs/**"
      - "pyproject.toml"
      - "requirements.txt"
      - ".github/**"

jobs:
  offline-tests:
    name: offline-tests (NO_NETWORK, OPENAI_API_MOCK)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          # Install project (editable) to ensure imports like `from app...` work
          if [ -f pyproject.toml ]; then
            pip install -e ".[dev]" || pip install -e .
          fi
          pip install pytest pytest-cov

      - name: Run pytest (offline)
        env:
          NO_NETWORK: "1"
          OPENAI_API_MOCK: "1"
          OPENAI_API_KEY: "dummy"   # satisfy OpenAI SDK init in offline mode
          MIN_SCORE: "0.0"          # lenient for offline CI
          PYTHONPATH: ${{ github.workspace }}
        run: |
          mkdir -p artifacts/test-results
          pytest -q --junitxml=artifacts/test-results/junit.xml 2>&1 | tee artifacts/test-results/pytest-stdout.txt

      - name: Upload test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results-offline
          path: artifacts/test-results/*
          if-no-files-found: warn

  online-tests:
    name: online-tests (pgvector smoke)
    # Only run if a Postgres DSN secret exists
    if: ${{ secrets.PG_DSN != '' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f pyproject.toml ]; then
            pip install -e ".[dev]" || pip install -e .
          fi
          pip install pytest pytest-cov

      - name: Prepare env (PG_DSN + OpenAI key fallback)
        run: |
          echo "CI_ONLINE=1" >> $GITHUB_ENV
          echo "NO_NETWORK=0" >> $GITHUB_ENV
          echo "PG_DSN=${{ secrets.PG_DSN }}" >> $GITHUB_ENV
          # If OPENAI_API_KEY secret is not set, use a harmless dummy to satisfy SDK import
          if [ -z "${{ secrets.OPENAI_API_KEY }}" ]; then
            echo "OPENAI_API_KEY=dummy" >> $GITHUB_ENV
          else
            echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> $GITHUB_ENV
          fi
          echo "PYTHONPATH=${GITHUB_WORKSPACE}" >> $GITHUB_ENV

      - name: Run pytest (online pgvector smoke)
        run: |
          mkdir -p artifacts/test-results-online
          pytest -q -m "online and pgvector" --junitxml=artifacts/test-results-online/junit.xml 2>&1 | tee artifacts/test-results-online/pytest-stdout.txt

      - name: Upload online artifacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results-online
          path: artifacts/test-results-online/*
          if-no-files-found: warn
